[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=63072000"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
